#!/bin/sh

### This script works in two steps
### 1.a. if not exist, cloene reposetory
### 1.b. keep git repositorys up to date
### 2. if SD card is mounted -> sync local git repository to SD

### On the bottom is a own function to sync UberGuidoz.
 
### Set variables - start 
## defaults
giturl=""
module=""
target=""
sdcard=/media/$USER/BENNIE
gitroot=~/git

## Overwrite defaults by conf file
confFile=./syncFlipperGit.conf
[ -f $confFile ] && { . $confFile ; }

### Set variables - stop

checkRequirement() {
	[ ! -x "$(command -v $1)" ] && { echo "$1 is not installed"; exit 1 ; }
}

checkRequirement rsync
checkRequirement git


gitSync () {

## Overwrite defaults and conf file by arguments
while getopts g:m:t:s:r: flag
do
    case "${flag}" in
        g) giturl=${OPTARG};;
        m) module=${OPTARG};;
        t) target=${OPTARG};;
        s) sdcard=${OPTARG};;
        r) gitroot=${OPTARG};;
    esac
done


	gitpath=$gitroot/$(basename $giturl)

	if [ $# -lt 2 ]; then
		echo "Usage: $(basename $0) -g <gitURL> -m <module> [-t target]"
		echo "<module>: badusb infrared nfc subghz ibutton music_player"
		exit 1
	fi

	# check if subpath on SD is okay
	case $module in
		badusb|infrared|nfc|subghz|ibutton|music_player) ;;
		*) echo "Allowed <module>: badusb infrared nfc subghz ibutton music_player" ; exit 1;;
	esac

	# If no SD subpath target is given, copy to subpath
	
	[ -z $target ] && { target=$(basename $giturl) ; }

	# If local git repo doesn't exist, clone first.
	[ ! -d "$gitpath" ] && { cd $gitroot && git clone --recursive $giturl; }
	cd $gitpath && git pull

	# If SD Card is mounted (mointpoint exist)
	# Some repository are often moving files around. --delete will take care of that.
	if [ -d "$sdcard" ]; then
		rsync -rv --checksum --delete $gitpath/ $sdcard/$module/$target/
		echo "Size on SD: " $(du -hs $sdcard/$module/$target)
	fi

	echo "Local size: " $(du -hs $gitpath)
}


#####################################################################
### The UberGuidoZ is a large collection of 3,5 GB valuable files.
### Some ressources are redundant to other repositorys.
### It is harder to navigate on the flipper, so I replaced some dirs.
### Feel free to comment any path, to reduce the size on SD

guidoSync () {
	gitpath=$gitroot/$(basename $1)
	
	# If local git repo doesn't exist, clone first.
	[ ! -d "$gitpath" ] && { cd $gitroot && git clone --recursive $1; }
	cd $gitpath && git pull

	# If SD Card is mounted (mointpoint exist)
	# Some repository are often moving files around. --delete will take care of that.
	if [ -d "$sdcard" ]; then
		rsync -rv --checksum --delete $gitpath/NFC/ $sdcard/nfc/guidoz/
		rsync -rv --checksum --delete $gitpath/Sub-GHz/ $sdcard/subghz/guidoz/
		rsync -rv --checksum --delete $gitpath/subplaylist/ $sdcard/subplaylist/
		rsync -rv --checksum --delete $gitpath/unirf/ $sdcard/unirf/
		rsync -rv --checksum --delete $gitpath/BadUSB/ $sdcard/badusb/guidoz/
		rsync -rv --checksum --delete $gitpath/picopass/ $sdcard/picopass/
		rsync -rv --checksum --delete $gitpath/Wav_Player/ $sdcard/wav_player/
		rsync -rv --checksum --delete $gitpath/Music_Player/ $sdcard/music_player/guidoz/
		echo "Size of dumps on SD: " $(du -hs --total $sdcard/nfc/guidoz/ $sdcard/subghz/guidoz/ $sdcard/subplaylist/ $sdcard/unirf/ $sdcard/badusb/guidoz/ $sdcard/picopass/)
		echo "Size of music on SD: " $(du -hs --total $sdcard/wav_player/ $sdcard/music_player/)
	fi
	
	echo "Local size: " $(du -hs $gitpath)
}

starnewSync () {
	gitpath=$gitroot/$(basename $1)
	
	# If local git repo doesn't exist, clone first.
	[ ! -d "$gitpath" ] && { cd $gitroot && git clone --recursive $1; }
	cd $gitpath && git pull

	# If SD Card is mounted (mointpoint exist)
	# Some repository are often moving files around. --delete will take care of that.
	if [ -d "$sdcard" ]; then
		rsync -rv --checksum --delete $gitpath/StarButton/ $sdcard/ibutton/StarButton/
		rsync -rv --checksum --delete $gitpath/StarRFID/ $sdcard/rfid/StarRFID/
		echo "Size of dumps on SD: " $(du -hs --total  $sdcard/ibutton/StarButton/ $sdcard/rfid/StarRFID/)
	fi
	
	echo "Local size: " $(du -hs $gitpath)
}

cd ~
